In [1]:
import numpy as np


In [2]:
# vraag 1 
data = np.array(["Mercedes", "pear", "antipasta", "ananas"])
data

In [3]:
# vraag 2 
for i in range (0, 4):
    print (data[i], end =" ")
print()

Mercedes pear antipasta ananas 


In [4]:
# vraag 3
one =np.ones(15, dtype=int)
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
# vraag 4 
vier = np.random.randint(1, 11, size=6)
vier

array([ 2, 10,  3, 10,  4,  4])

In [6]:
# vraag 5
vijf = np.random.randint(1, 21, size=(3, 4))
vijf

array([[ 2, 10,  8,  6],
       [11, 13,  9,  3],
       [ 2,  3, 18,  7]])

In [7]:
# vraag 6
print("Dimensies: ",vijf.ndim,"\nShape: ", vijf.shape,"\nSize: ",vijf.size)

Dimensies:  2 
Shape:  (3, 4) 
Size:  12


In [8]:
# vraag 7
print(vijf[1,1])

13


In [9]:
# vraag 8
acht = np.arange(2, 21, 2)
acht

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# vraag 9
negen = np.arange(2, 10, 2)
negen

array([2, 4, 6, 8])

In [11]:
# vraag 10
print(negen[:4])

[2 4 6 8]


In [12]:
# vraag 11
print(negen[-4:])

[2 4 6 8]


In [13]:
# vraag 12
x = np.array([1, 2, 3], dtype=str)
y = np.array([3, 2, 1], dtype=str)
twaalf = np.concatenate((x, y))
twaalf

array(['1', '2', '3', '3', '2', '1'], dtype='<U1')

In [14]:
# vraag 13
x = np.array([-2, -1, 0, 1, 2])
dertien = np.abs(x)
dertien

array([2, 1, 0, 1, 2])

In [15]:
# vraag 14
veertien = np.linspace(0, 20, 11, dtype= int)
veertien

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
# vraag 15
x = np.array([1, 2, 4, 100])
# a 
print("ln(x) =", np.log(x))
# b
print("log2(x) =", np.log2(x))
# c
print("log10(x) =", np.log10(x))

ln(x) = [0.         0.69314718 1.38629436 4.60517019]
log2(x) = [0.         1.         2.         6.64385619]
log10(x) = [0.         0.30103    0.60205999 2.        ]


In [17]:
# vraag 16
zestien = np.array(['eric', 'paul', 'sean'])
# a 
ZESTIEN = np.char.upper(zestien)
print(ZESTIEN)
# b
Zestien = np.char.capitalize(zestien)
print(Zestien)

['ERIC' 'PAUL' 'SEAN']
['Eric' 'Paul' 'Sean']
